remote-theme: minima
theme: minima

# Site wide configuration

title: Sameer D'Costa's Blog
author: Sameer D'Costa
github_username: sameerd
locale: en_US
description: Learning from Data
logo: site-logo.png
search: true
url: https://sameerd.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
encoding: utf-8
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

github: [metadata]

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess", "_pages" ]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "*.Rmd", "R", "Makefile", "cache"]


excerpt_separator: <!--more-->


# Site owner
owner:
  name: Sameer D'Costa 
  avatar: bio-photo.jpg
  email: sameerdcosta@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: sameerd
  stackexchange: https://stackoverflow.com/users/342362/sameer
  linkedin: sameerdcosta
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
